### ISSUE TITLE
Mod crashes single player and server due to Advancement ticking

### ISSUE THREAD

**Issue by TheWanderingTrader** [ultrakoxxd/idontwantportalyet#7]
Every time I launch a server or single player world it crashes with the following error-
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.advancements.Advancement net.minecraftforge.event.entity.player.AdvancementEvent$AdvancementEarnEvent.getAdvancement()'
	at com.ultrakox.idontwantportalyet.events.modEvents.portalAvancementMade(modEvents.java:88) ~[idontwantportalyet-1.20-1.9.jar!/:1.20-1.9] {re:classloading}
	at com.ultrakox.idontwantportalyet.events.__modEvents_portalAvancementMade_AdvancementEarnEvent.invoke(.dynamic) ~[idontwantportalyet-1.20-1.9.jar!/:1.20-1.9] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:58) ~[eventbus-6.2.0.jar!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:300) ~[eventbus-6.2.0.jar!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:281) ~[eventbus-6.2.0.jar!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:170) ~[forge-1.20.4-49.0.49-universal.jar!/:?] {re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.onAdvancementEarned(ForgeEventFactory.java:766) ~[forge-1.20.4-49.0.49-universal.jar!/:?] {re:classloading}
	at net.minecraft.server.PlayerAdvancements.m_135988_(PlayerAdvancements.java:189) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,re:classloading,pl:mixin:APP:iceberg.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.advancements.CriterionTrigger$Listener.m_13686_(CriterionTrigger.java:21) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:71) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.m_43153_(InventoryChangeTrigger.java:46) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading}
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.m_43149_(InventoryChangeTrigger.java:42) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer$2.m_7934_(ServerPlayer.java:239) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150407_(AbstractContainerMenu.java:219) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_38946_(AbstractContainerMenu.java:171) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_38893_(AbstractContainerMenu.java:124) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerPlayer.m_143399_(ServerPlayer.java:407) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:forgivingvoid.mixins.json:ServerPlayerAccessor,pl:mixin:APP:mixins.additionalplacements.json:MixinServerPlayer,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_143429_(ServerPlayer.java:412) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:forgivingvoid.mixins.json:ServerPlayerAccessor,pl:mixin:APP:mixins.additionalplacements.json:MixinServerPlayer,pl:mixin:A}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:243) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,xf:fml:openpartiesandclaims:xaero_pac_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,re:classloading,xf:fml:openpartiesandclaims:xaero_pac_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,pl:mixin:A}
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.m_293007_(ServerConfigurationPacketListenerImpl.java:125) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.m_5797_(ServerboundFinishConfigurationPacket.java:20) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading}
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.m_5797_(ServerboundFinishConfigurationPacket.java:7) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.lambda$checkThreadAndEnqueue$0(PacketUtils.java:42) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[srg:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:198) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:788) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.forge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.forge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:163) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:771) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.forge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:765) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.forge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:140) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:750) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.forge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:679) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.forge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:256) ~[forge-1.20.4-49.0.49-client.jar!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.forge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
	
	
	A fix to this is simply removing the Idontwantportalyet mod.

**Comment by ultrakoxxd** [comment]
It would be great if you can send me list of mods you are using so i can check what mod is causing that and try to fix it
